### ISSUE TITLE
type: 'lineWithErrorBars' does not respond to values entered for pointRadius or pointHitRadius

### ISSUE THREAD

**Issue by gubsy420** [sgratzl/chartjs-chart-error-bars#111]
As the title states, I cannot get a dataset with type: 'lineWithErrorBars' to respond to changes I make to the values of pointRadius or pointHitRadius. It is 100% possible I am doing something wrong, however the other line dataset I have in the same chart that is not using error bars responds to changes in those two parameters as expected.

**To Reproduce**

1. Add a dataset to a chart with type: 'lineWithErrorBars'
2. Add parameters pointRadius or pointHitRadius
3. Change the value to anything other than default
4. Draw chart

**Expected behavior**

I expect the point radius and the point hit radius to change when I define different values for them.

**Screenshots**

**Context**

- Version: v4.4.2: [chartjs-chart-error-bars](https://www.jsdelivr.com/package/npm/chartjs-chart-error-bars)
- Browser: Chrome Desktop

**Additional context**

**Comment by sgratzl** [comment]
try `pointWithErrorBarRadius` instead of `pointRadius` since a different element is used to combine the error bar and the point.
