### ISSUE TITLE
Feature Request: Rendering whiskers after the whole graph is rendered

### ISSUE THREAD

**Issue by marconett** [sgratzl/chartjs-chart-error-bars#113]
I am referring to BarWithErrorBar only here, as this is what I use, but it is likely a feature that would impact other chart types as well.

Currently, it seems that each error-bar (and its whiskers) is rendered right after the associated bar in a Bar Chart is rendered.\
This is fine when it comes to rendering the error-bars themselves (as those are wholly on top of the bar itself). But the whiskers can appear behind adjacent bars, if working with charts that displays bars close together or directly next to each other.

You can see this on my example screenshot:

<img width="600" alt="order" src="https://github.com/user-attachments/assets/5e22ff7b-1300-4b76-957e-59edd738a54e">

I drew pink arrows onto the screenshot, pointing to occurrences of other bars overlapping whiskers.

It would be great if the whiskers would be rendered after all bars are rendered or to make the render order configurable. This would lead to cleaner looking (and imo more correct) charts.

Thank you for open sourcing and maintaining this great library!

**Comment by sgratzl** [comment]
that is not possible in they way chart.js renders object. The bar and the whiskers are rendered as one unit. 

have you considered changing the style of the errors bars instead (e.g. a fixed fixed and within the bar not sticking out of it?

**Comment by marconett** [comment]
Thank you for the quick reply!

I looked into the source and understand why this isn't possible with the way this library is built.

Just adding some context for future reference if someone stumbles upon this issue.

There's a hack that forces the requested behaviour by replacing the function body of: https://github.com/sgratzl/chartjs-chart-error-bars/blob/a4819cddf890fc632c5d6c959bbebaae489099d3/src/elements/BarWithErrorBar.ts#L15

with the following:

```js
ctx.save();
ctx.globalCompositeOperation = 'destination-over';
super.draw(ctx);
ctx.restore();

renderErrorBar(this, ctx);
```

This can have ugly side effects tho but might be considered "good enough" depending on the use case.

In order to solve the problem properly, the best way forward would be to not use this library and draw the error bars after the whole dataset is drawn, for example with [chartjs-plugin-annotation](https://www.chartjs.org/chartjs-plugin-annotation/) or by implementing a new plugin.
