### ISSUE TITLE
Add style options to readme?

### ISSUE THREAD

**Issue by john-rock** [sgratzl/chartjs-chart-error-bars#14]
Great plugin but I just had to go digging to find out how to change the error bar and whisker color.

Happy to help with that if needed.

**Comment by sgratzl** [comment]
what about adding pointers to their TypeScript interfaces such as 

https://github.com/sgratzl/chartjs-chart-error-bars/blob/main/src/elements/render.ts#L17 

for styling and 

https://github.com/sgratzl/chartjs-chart-error-bars/blob/db83b483e77435949403a7a6ec20013b403018f0/src/controllers/base.ts#L3

for the data structure

**Comment by sgratzl** [comment]
see https://github.com/sgratzl/chartjs-chart-error-bars/tree/dev#styling-1

**Comment by USMortality** [comment]
It remains unclear how to configure the error bar color, i.e. where to add the specific option...
