### ISSUE TITLE
lineWithErrorBars

### ISSUE THREAD

**Issue by mahadev-Pandhare** [sgratzl/chartjs-chart-error-bars#17]
Hi Team,
We are facing issue to create Line chart with error bars(lineWithErrorBars). We are getting issue with canvas context issue s undefined,
Where same configuration working with barWithErrorBars.
So if possible can you provide the reference code for  lineWithErrorBars . We are using chart js 3.6.0  version and chartjs-chart-error-bars/v/3.6.0 version.
above mentioned npm packges we are using with angular 12.

Thanks,
M.dev

**Comment by sgratzl** [comment]
without code it is impossible to tell what is going on, since https://codepen.io/sgratzl/pen/rNGvqXb 
![image](https://user-images.githubusercontent.com/4129778/148071278-9298730b-16e2-4830-bf22-9d6524368ea6.png)
 works just fine

**Comment by mahadev-Pandhare** [comment]
We are using angular 12 with chart js 3.6.2 version.
For the error bars we r using version ^3.6.0. npm package, As suggested  in link below:
https://www.npmjs.com/package/chartjs-chart-error-bars

We are taking canvas reference using @viewChild  decorator in Angular.
We r able to render barWithErrorBrs controller  bar chrt , But when we use lineWithErrorBars , its having error as undefined context.

So please suggest if we need to do any config changes.

**Comment by GUI2015** [comment]
Continue to @mahadev-Pandhare  comment, we are getting below error in console. It is happening with only **lineWithErrorBars**
![image](https://user-images.githubusercontent.com/7512122/148206961-f346ae6a-4530-4cfc-9ce3-4f8ae121d55e.png)

**Comment by GUI2015** [comment]
While doing analysis we found that **DatasetController** getting called twice for **lineWithErrorBars**, any idea why it is getting called twice? does any configuration is required to stop second call?


![image](https://user-images.githubusercontent.com/7512122/148214341-e5860783-8d10-482d-9fa1-1f3aa19381af.png)

**Comment by sgratzl** [comment]
can you create a codesandbox or similar with a setup that is showing this error? Otherwise, I don't know how to investigate this error since it works fine in the codepen I sent before
