### ISSUE TITLE
elements.point configurations does not apply in lineWithErrorBars

### ISSUE THREAD

**Issue by mohoma** [sgratzl/chartjs-chart-error-bars#19]
I,m using `lineWithErrorBars`, and when I try to set `elements.point` configs both locally on chart object and through `Chart.defaults` it seems that desired configuration does not apply.

**To Reproduce**
```javascript
Chart.defaults.elements.point.radius = 10

//or

new Chart(document.getElementById('canvas').getContext('2d'), {
            type: 'lineWithErrorBars',
            options: {
                elements: {
                    point:{
                        radius: 10
                    }
                }
            },
            data: {
                labels: labels,
                datasets: datasets
            },
        });

```

**Context**

- Version: chart.js@3.6.0, chartjs-chart-error-bars@3.6.0
- Browser: Chrome v97.0

Thank you in advance for your great work.

**Comment by sgratzl** [comment]
can you create a running example, e.g. in codepen comparing your desired output using the `line` chart type and the bug you experienced using `lineWithErrorBars`

**Comment by mohoma** [comment]
Here is the example containing the two modes, the first chart is the normal `line` chart and the second one is `lineWithErrorBars`.
[codepen](https://codepen.io/mohoma/pen/xxPgzQX)

Thank you for your response

**Comment by mohoma** [comment]
It works perfectly, thank you man
