### ISSUE TITLE
ie11 compatibility

### ISSUE THREAD

**Issue by shraddha0110** [sgratzl/chartjs-chart-error-bars#5]
**Describe the bug**
When I try to use chartjs error bar library on ec2 (centOS) in AWS with IE11, I get the following error: Object doesn't support property or method 'assign'. But I do not get this issue with Google Chrome or Firefox. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sgratzl** [comment]
should be fixed with the latest version https://github.com/sgratzl/chartjs-chart-error-bars/releases/tag/v1.2.1
