### ISSUE TITLE
String Parsing with Min / Max Values

### ISSUE THREAD

**Issue by drskigen** [sgratzl/chartjs-chart-error-bars#51]
When I attempt to generate an Error Bar chart using string data for data points, the error bars do not generate. If I use numerical values (float or int) the error bars generate.

This is a minor bug and I can get around it by just ensuring data is numerical, but the behavior seems inconsistent with how data is handled for the default Chart.js data points.

Side note: thank you for the excellent plugin!

**To Reproduce**

1. Generate a basic Error Bar chart with min / max values as a string data type.
2. Chart will load with normal data points, but error bars do not load.

**Expected behavior**

Min / max data points allow string and numerical data.

**Context**

- Version: 4.2.0
- Browser: Any

**Comment by sgratzl** [comment]
IMO you should always provide numbers, I'm not a fan of magically parsing string to numbers and TypeScript typings also are not designed in that way.

**Comment by drskigen** [comment]
That is fair. I don't disagree, I wanted to update the data type to numerical anyway and only discovered this by accident. I filed a bug because it's inconsistent with the core behavior, but you can feel free to close this if this is intended behavior for the plugin.

**Comment by sgratzl** [comment]
closing wontfix
