### ISSUE TITLE
LineWithErrorBars does not render when using scale of type time

### ISSUE THREAD

**Issue by santilland** [sgratzl/chartjs-chart-error-bars#55]
When trying to render LineWithErrorBars having an x Axis scale of type "time" nothing is rendered.
Using the exact same config but changing to scatterWithErrorBars works as expected.

**Context**
I'm relatively sure this is not browser related, using chartjs>4

**Additional context**
I think the issue is related to this check:
https://github.com/sgratzl/chartjs-chart-error-bars/blob/main/src/controllers/LineWithErrorBarsController.ts#L61
Maybe adding "time" as check for also being a "hasNumberIScale"  might do the trick.

**Comment by sgratzl** [comment]
can you provide an example? e.g. codepen, codesandbox, ... cannot reproduce right now

**Comment by santilland** [comment]
It seems codesandbox is having some issues right now, hope this loads, should show what i mean:
https://codesandbox.io/s/agitated-chandrasekhar-qe63we?file=/src/index.js

**Comment by sgratzl** [comment]
fixed in 4.1.2

**Comment by santilland** [comment]
Looks good! Thanks for the quick fix!
