### ISSUE TITLE
Is there a .js file to import the plugin?

### ISSUE THREAD

**Issue by pguillem** [sgratzl/chartjs-chart-error-bars#58]
Great plugin!
Is there a .js file we can import to load the plugin into sites?
I don't use NPM and wondered if it was available somewhere.

I can see the samples point to a "build" directory that contains the js, but it is not in the git tree.

Thanks in advance
Pedro

**Comment by sgratzl** [comment]
no this repo doesn't contain the binaries but you can download the file from npm via a cdn such as 

https://unpkg.com/chartjs-chart-error-bars

**Comment by pguillem** [comment]
Worked like a charm
Thank you very much!
