### ISSUE TITLE
Hello Can you please share how to use chart-error-bars on Line Graph? 

### ISSUE THREAD

**Issue by DevanshuBrahmbhatt** [sgratzl/chartjs-chart-error-bars#59]
It would be great if ...

**User story**

**Additional context**

**Comment by domef** [comment]
I agree, some more examples would be great.

**Comment by sgratzl** [comment]
take a look at the samples folder: https://github.com/sgratzl/chartjs-chart-error-bars/blob/main/samples/lines.html
