### ISSUE TITLE
chart-error-bars on Line Graph

### ISSUE THREAD

**Issue by DevanshuBrahmbhatt** [sgratzl/chartjs-chart-error-bars#60]
Can you please share how to use chart-error bars on Line Graph? 
I am trying to use 'lineWithErrorBars' but it is not working out.

**Comment by Fanta104** [comment]
Hey, I think i can help you a few steps further 😀
I guess you have problem with adressing the dataset.

First you have to use the type: "lineWithErrorBars" at creation.
```
var ctx = document.getElementById('myChart').getContext('2d');
  mainchart = new Chart(ctx , {
  type: "lineWithErrorBars",
  data: data, 
  options: options
});
```
The main difference to the "normal" type:"line" chart is the array you set in 
`yourchart.data.datasets[x].data = ...`
You have to follow this scheme:
`[{y: arr1, yMin: arr2, yMax: arr3}, {y: arr1, yMin: arr2, yMax: arr3}, ...]`

In my case this worked:
```
var arr1 = rawdata[3].map(obj => obj.AverageValue);
var arr2 = rawdata[3].map(obj => obj.MinValue);
var arr3 = rawdata[3].map(obj => obj.MaxValue);

let result = [];

for (let i = 0; i < arr1.length; i++) {
	result.push({ y: arr1[i], yMin: arr2[i], yMax: arr3[i] });
}

mainchart.data.datasets[0].data = result;
```

Unfortunately I struggle to customize my other Lines. I added three lines to visualize deviating values and the aimed value.
I'd like to remove the points in these with the pointBorderWidth: 0 like it is working in my other type:"line" chart. But as soon I change the to type:"lineWithErrorBars" the dots come back 😣
```
datasets: [{
		label: '98%',
		pointRadius: 0,
		pointHitRadius: 0,
		borderColor: "rgba(241,194,50,1)",
		backgroundColor: "rgba(241,194,50,1)"		
	},
	{
		label: 'Heads',
		pointRadius: 0,
		pointHitRadius: 0,
		borderColor: "rgba(166,77,121,1)",
		backgroundColor: "rgba(166,77,121,1)"
	}
]
```
![grafik](https://user-images.githubusercontent.com/28059259/235104477-acf4acf2-a492-46d1-aa90-662722c9be4a.png)

A small guide on how to do the basics and customizing with the standard chart.js commands would be very appreciated 🤗

**Comment by sgratzl** [comment]
re "pointBorderWidth",

since it is a point with an error bar, try setting `pointWithErrorBarBorderWidth`

**Comment by quangthuanhoang** [comment]
> 

Hi, can you show me the details of your code? I also have the same problem. This is my code:
```
  new ChartJS(document.getElementById('canvas').getContext('2d'), {
      type: 'lineWithErrorBars',
      data: {
        datasets: [
          {
            data: [
              {
                y: 4,
                yMin: 1,
                yMax: 6,
              },
              {
                y: 2,
                yMin: 1,
                yMax: 4,
              },
            ],
          },
        ],
      },
      options: {
        // animation: false
      },
    });
```
