### ISSUE TITLE
AMD import of helpers

### ISSUE THREAD

**Issue by ThomasK0lasa** [sgratzl/chartjs-chart-error-bars#74]
You have bug when importing helpers as AMD. Chart.js docs says:

> In UMD, helpers are available through Chart.helpers. In ESM, they are imported from chart.js/helpers

Fix in index.umd
add new line 13:
`if (!helpers) helpers = chart_js.helpers;`
modify line 10 (remove chart.js/helpers):
`typeof define === 'function' && define.amd ? define(['exports', 'chart.js'], factory) :`

**Comment by sgratzl** [comment]
hm. I don't know how to configure rollup to adapt AMD configurations, There is only https://rollupjs.org/configuration-options/#output-globals which is correctly set for the global variable setup. 

in your scenario, cannot you define a AMD module that defines `chart.js/helpers` as chart.js -> helpers?
