### ISSUE TITLE
Error bar color: Use default dataset color if not provided

### ISSUE THREAD

**Issue by wwerkk** [sgratzl/chartjs-chart-error-bars#96]
Lack of default color for error bars decreases the readability of line plots, when multiple datasets are plotted:
<img width="380" alt="Screenshot 2024-04-09 at 12 03 25" src="https://github.com/sgratzl/chartjs-chart-error-bars/assets/32481425/a0c12dbf-ffe7-45ae-a223-496d49d0e656">
https://codepen.io/wwerkk/pen/poBVjZb

It would be great to use default colors of the dataset, if error bar color is not specified, akin to the datavisyn plugin:
<img src="https://user-images.githubusercontent.com/5220584/43774415-4ab5ae88-9a49-11e8-813d-48d607d45225.png">
https://github.com/datavisyn/chartjs-plugin-error-bars?tab=readme-ov-file#options

There is a way of working around this, but it's unwieldy as afaik the Chart object has to be created first:
```
        const chart = new Chart(canvas, {
          type: "lineWithErrorBars",
          data,
          options,
        });
        for (let dataset of chart.data.datasets) {
          dataset.errorBarColor = dataset.borderColor;
          dataset.errorBarWhiskerColor = dataset.borderColor;
        }
```

**Comment by sgratzl** [comment]
the colors of the dataset are assigned by the "Colors" plugin of chart.js (https://www.chartjs.org/docs/latest/general/colors.html#default-color-palette). The colors plugin doesn't know about this plugin and thus doesn't assign the same colors.

**Comment by sgratzl** [comment]
cannot fix
